[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"

[build]
  command = "yarn build"
  publish = "dist"

[functions]
  directory = "site/functions"

[context.deploy-preview]
  command = "yarn build:preview"

[dev]
  framework = "hugo"
  targetPort = 3000

# OAuth function mount
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200
  
# Block /admin on the public hosts (return 404 or redirect somewhere safe)
[[redirects]]
  from = "/admin/*"
  to = "/404.html"           # or "/" if you prefer
  status = 404               # could be 401/403 too
  conditions = { Host = ["driftcascade.com", "www.driftcascade.com"] }
  force = true               # override static file

# On the CMS host, route everything to the Decap SPA
[[redirects]]
  from = "/*"
  to = "/admin/index.html"
  status = 200
  conditions = { Host = ["cms.driftcascade.com"] }
  force = true               # override any static matches on cms host

[[headers]]
  for = "/admin/*"
  [headers.values]
    # Tight default; open only what Decap needs
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://unpkg.com https://cdn.jsdelivr.net 'unsafe-eval';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https:;
      connect-src 'self' https://api.github.com https://github.com;
      font-src 'self' https:;
      worker-src 'self' blob:;
      frame-ancestors 'none';
      base-uri 'none';
    """
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
    Cache-Control = "no-store"
    X-Robots-Tag = "noindex, nofollow"


[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    record = true