[build.environment]
  NETLIFY_USE_YARN = "true"
  YARN_VERSION = "1.22.17"

[build]
  command = "yarn build"
  publish = "dist"

[functions]
  directory = "site/functions"

[context.deploy-preview]
  command = "yarn build:preview"

[dev]
  framework = "hugo"
  targetPort = 3000

# OAuth function mount
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200
  
# Redirect cms subdoimain to admin page
[[redirects]]
  from = "/*"
  to = "/admin/index.html"
  status = 200
  conditions = { Host = ["cms.driftcascade.com"] }

# Security headers for admin assets
[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' https://unpkg.com https://cdn.jsdelivr.net; connect-src 'self' https://api.github.com https://github.com"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
    Cache-Control = "no-store"
    X-Robots-Tag = "noindex, nofollow"

[[plugins]]
  package = "netlify-plugin-cypress"

  [plugins.inputs]
    record = true