baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Drift Cascade"
buildFuture = true

[permalinks]
blog = "/blog/:slug/"

# RSS enabled for blog content
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration

[taxonomies]
  tag = "tags"

[params]
images = ["img/og-image.jpg"]
description = "Drift Cascade - Development logs, design thoughts, and project updates for strategy, emergent systems, and real-time tactics games"

# Table of Contents configuration
[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    hl_inline = false
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "tokyonight-storm"
    tabWidth = 4
  
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.extensions]
      typographer = true
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true

# RSS configuration
[outputs]
home = ["HTML", "RSS"]