baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Drift Cascade"
buildFuture = true

# RSS and categories disabled, tags enabled
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS"]

[taxonomies]
  tag = "tags"

[params]
images = ["img/og-image.jpg"]