backend:
  name: github
  repo: DriftCascade/DriftCascade-Site
  branch: main

local_backend: true

publish_mode: editorial_workflow
site_url: "https://driftcascade.com"

media_folder: "site/static/uploads"
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog Posts" # Used in the UI, ie.: "New Post"
    folder: "site/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "string", required: false, hint: "Author name (e.g., 'Drift Cascade Interactive')"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - label: "Tags"
        name: "tags"
        widget: "string"
        required: false
        hint: "Enter tags separated by commas (e.g., 'Game Development, Unity, Tutorial')"
      - {label: "Image", name: "image", widget: "image", required: false, choose_url: false}
      - {label: "Image Alt Text", name: "image_alt", widget: "string", required: false, hint: "Descriptive text for screen readers (e.g., 'Drift Cascade Interactive logo featuring circuit-inspired design')"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "games"
    label: "Games"
    folder: "site/content/games"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "weight", widget: "number", hint: "Lower numbers appear first (1, 2, 3, etc.)", default: 10}
      - {label: "Status", name: "status", widget: "string", hint: "e.g., Active Development, On Hold / Alpha"}
      - {label: "Blog Tag", name: "tag", widget: "string", hint: "Tag name to link to blog posts (e.g., 'Salvage Wars', 'CityWar')", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Title Image", name: "titleImage", widget: "image", required: false, hint: "Main title/logo image for the game"}
      - {label: "Concept Art", name: "conceptArt", widget: "image", required: false, hint: "Concept art or promotional image for the game"}
      - label: "Primary CTA"
        name: "primaryCta"
        widget: "object"
        required: false
        fields:
          - {label: "Text", name: "text", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
      - label: "Secondary CTAs"
        name: "secondaryCtas"
        widget: "list"
        required: false
        fields:
          - {label: "Text", name: "text", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Tagline", name: "tagline_main", widget: "string"}
          - {label: "Sub Tagline", name: "tagline_sub", widget: "string"}
          - label: "Mission"
            name: "mission"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Text", name: "text", widget: "text"}
          - {label: "Featured Game", name: "featured_game", widget: "string", hint: "Enter the game filename (e.g., 'salvage-wars' or 'citywar')"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - file: "site/content/games/_index.md"
        label: "Games Page"
        name: "games_page"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string", hint: "Short tagline displayed below the title"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown", hint: "Full page content in markdown format. Supports headings, lists, links, and more."}
      - file: "site/content/blog/_index.md"
        label: "Blog Page"
        name: "blog_page"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown", hint: "Introduction text that appears before the blog post list"}
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/tags.json"
        label: "Blog Tags"
        name: tags
        fields:
          - label: Tags
            name: tags
            widget: list
            fields:
              - {label: "Display Name", name: "name", widget: "string"}
              - {label: "Slug", name: "slug", widget: "string", hint: "URL-friendly version (lowercase, hyphens)"}
      - file: "site/data/footer.json"
        label: Footer
        name: footer
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Blurb, name: blurb, widget: text}
      - file: "site/hugo.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
