backend:
  name: github
  repo: DriftCascade/DriftCascade-Site
  branch: main

local_backend: true

publish_mode: editorial_workflow
site_url: "https://driftcascade.com"

media_folder: "site/static/uploads"
public_folder: "/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog Posts" # Used in the UI, ie.: "New Post"
    folder: "site/content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "games"
    label: "Games"
    folder: "site/content/games"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Status", name: "status", widget: "string", hint: "e.g., Active Development, On Hold / Alpha"}
      - {label: "Description", name: "description", widget: "text"}
      - label: "Primary CTA"
        name: "primaryCta"
        widget: "object"
        required: false
        fields:
          - {label: "Text", name: "text", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
      - label: "Secondary CTAs"
        name: "secondaryCtas"
        widget: "list"
        required: false
        fields:
          - {label: "Text", name: "text", widget: "string"}
          - {label: "Link", name: "link", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Main Tagline", name: "tagline_main", widget: "string"}
          - {label: "Sub Tagline", name: "tagline_sub", widget: "string"}
          - label: "Mission"
            name: "mission"
            widget: "object"
            fields:
              - {label: "Heading", name: "heading", widget: "string"}
              - {label: "Text", name: "text", widget: "text"}
              - {label: "Focus", name: "focus", widget: "string"}
          - label: "Featured"
            name: "featured"
            widget: "object"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}
              - {label: "Link", name: "link", widget: "string"}
              - {label: "Button Text", name: "button_text", widget: "string"}
              - {label: "Image Placeholder", name: "image_placeholder", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - file: "site/content/games/_index.md"
        label: "Games Page"
        name: "games_page"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string", hint: "Short tagline displayed below the title"}
          - {label: "Body", name: "body", widget: "markdown", required: false}
      - file: "site/content/about/_index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Page Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown", hint: "Full page content in markdown format. Supports headings, lists, links, and more."}
      - file: "site/content/blog/_index.md"
        label: "Blog Page"
        name: "blog_page"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Content", name: "body", widget: "markdown", hint: "Introduction text that appears before the blog post list"}
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "site/data/footer.json"
        label: Footer
        name: footer
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Blurb, name: blurb, widget: text}
      - file: "site/hugo.toml"
        label: Hugo Config
        name: config
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
